### ISSUE TITLE
company files

### ISSUE THREAD

**Issue by laurielounge** [uptick/pymyob#16]
<EDIT - My bad, was using not the most recent version
Comment left so you know someone's checking out your work>

Hi there,

< cred.authenticate_companyfile(company_id, <username>, <password>)>

That's not really a thing, is it? Can't see it referred to in any of the code... is that for the version 1 of the myob API perhaps?

Or have I totally gone off on the wrong track here?

What I mean is, running through the instructions (which are a work in  progress, no probs), I get to this point;

cred.authenticate_companyfile(company_id, <username>, <password>)

... and it all stops. Just looking at a php example that's working (AccountRight_OAUTH_sample_php) to see what can be done here.

**Comment by jarekwg** [comment]
Hi @laurielounge,

Yep, this was a new addition in v1.0.
Also worth noting, which I might go back and add to the patch notes, is that the storage of the companyfile credentials has changed intenally in v1.0, so unless a database migration is added, your customers will need to re-connect their MYOB integration when you upgrade to this version.

Cheers,
