### ISSUE TITLE
company_files

### ISSUE THREAD

**Issue by laurielounge** [uptick/pymyob#17]
company_files = myob.companyfiles.all()

Not getting anything in this code. 

Following the debug, I can see the data in raw_companyfiles, but nothing seems to get returned except for 

[CompanyFile:
    contacts
    general_ledger
    inventory
    invoices
    purchase_bills
    purchase_orders]

In 

> /usr/local/lib/python3.6/site-packages/myob/api.py(39)all()
-> return [CompanyFile(raw_companyfile, self.credentials) for raw_companyfile in raw_companyfiles]
(Pdb) p raw_companyfiles 
[{'Id': '377a1687-408c-4647-a390-1b4c2ea1ff9d', 'Name': 'API Sandbox Demo 46', 'LibraryPath': 'API Sandbox Demo 46', 'ProductVersion': '2018.2', 'ProductLevel': {'Code': 30, 'Name': 'Plus'}, 'CheckedOutDate': None, 'CheckedOutBy': None, 'Uri': 'https://ar1.api.myob.com/accountright/377a1687-408c-4647-a390-1b4c2ea1ff9d', 'Country': 'AU', 'LauncherId': 'fd2874bb-9113-4c7d-afa6-4adeffd9d395', 'SerialNumber': '611837501826'}]

...and later...

> /usr/local/lib/python3.6/site-packages/myob/api.py(57)__init__()
-> self.credentials = credentials
(Pdb) p self.data
{'Id': '377a1687-408c-4647-a390-XXXXXXXX', 'Name': 'API Sandbox Demo 46', 'LibraryPath': 'API Sandbox Demo 46', 'ProductVersion': '2018.2', 'ProductLevel': {'Code': 30, 'Name': 'Plus'}, 'CheckedOutDate': None, 'CheckedOutBy': None, 'Uri': 'https://ar1.api.myob.com/accountright/377a1687-408c-4647-a390-XXXXXXX', 'Country': 'AU', 'LauncherId': 'fd2874bb-9113-4c7d-afa6-XXXXXXX', 'SerialNumber': '1234'}

And, alternatively, this works:

(Pdb) p myob.companyfiles._manager.all()
[{'Id': '377a1687-408c-4647-a390-XXXXXXXX', 'Name': 'API Sandbox Demo 46', 'LibraryPath': 'API Sandbox Demo 46', 'ProductVersion': '2018.2', 'ProductLevel': {'Code': 30, 'Name': 'Plus'}, 'CheckedOutDate': None, 'CheckedOutBy': None, 'Uri': 'https://ar1.api.myob.com/accountright/377a1687-408c-4647-a390-XXXXXXX', 'Country': 'AU', 'LauncherId': 'fd2874bb-9113-4c7d-afa6-XXXXXXX', 'SerialNumber': '1234'}]

Any thoughts?

**Comment by jarekwg** [comment]
Hehe hrmm,

This is not a bug, but it does look a little silly... I've made the repr print out what methods are available on the CompanyFile.

`myob.companyfiles.all()` does in fact return a list of available companyfiles. You can go right ahead and do:
```
comp = myob.companyfiles.all()[0]
comp.invoices.all()
```

I'll open an issue about adjusting this so that it doesn't look so absurd, or at least provides some info about the selected company file. Might end up moving stuff off the `__repr__` altogether and onto some dedicated `methods()` function for printing the methods instead..

**Comment by jarekwg** [comment]
Id: `comp.id`
Name: `comp.name`
everything else `comp.data`

I'll add this to the readme. 👍

**Comment by laurielounge** [comment]
Hi,

Dammit!

That was it. Thanks so much for your help.

**Comment by jarekwg** [comment]
Cheers,
