### ISSUE TITLE
Reponse 401

### ISSUE THREAD

**Issue by laurielounge** [uptick/pymyob#19]
Hi Jarek,

I'm seeing response 401 whenever I try and grab data.

(Pdb) cred.verified
True
(Pdb) cred.refresh()
(Pdb) p comp.id
'c4040fe7-dbb9-4bb2-XXX-cc2ba4ccbe16'
(Pdb) p comp.data
{'Id': 'c4040fe7-dbb9-4bb2-XXX-cc2ba4ccbe16'}
(Pdb) inv = comp.inventory.item()
*** myob.exceptions.MyobUnauthorized: (<Response [401]>, 'Unauthorized')

Doesn't seem to matter what I'm trying for. Have you seen this? Any ideas?

regards,

Laurie

**Comment by jarekwg** [comment]
Hi Laurie,

Have you checked that the account that you created the integration with has access to this information? I have seen 401s on some endpoints in the past, and they have usually been a result of an underprivileged user setting up the integration.

Have you checked whether you can access other endpoints? Can you access the list of company files?

Cheers,
Jarek

**Comment by laurielounge** [comment]
It was the credentials the client gave me that were the problem. The username was wrong. Problem is cred.authenticate_companyfile(id, user, pass) doesn't error (or does it?). I still got returned th ecompany details. It only fails when drawing from the (say) customers method.

Thanks for the idea though. Should have checked on the live Myob app to see if the cred worked.

Cheers Jarek

**Comment by jarekwg** [comment]
Heh, 

That's still a TODO: https://github.com/uptick/pymyob/blob/a7cf2d6eed05b516c8360c1a6a3799f2f99d89ab/myob/credentials.py#L34-L39
