### ISSUE TITLE
endpoint request

### ISSUE THREAD

**Issue by laurielounge** [uptick/pymyob#29]
Addition to the endpoints.py:

    'Sale/Order/': {
        'name': 'orders',
        'methods': [
            (ALL, '', 'order invoice type'),
            (CRUD, 'Item/', 'item type sales order'),
            (CRUD, 'Service/', 'service type sales order'),
        ]
    },
Cheers

**Comment by jarekwg** [comment]
Hi lauriellounge,

If you have time to add it yourself in a PR, and drop in a corresponding test, I can publish within the day, else I can get round to it some time this week.

Cheers,
