### ISSUE TITLE
Update flow to not require companyfile credentials passed.

### ISSUE THREAD

**Issue by jarekwg** [uptick/pymyob#33]
Users with SSO enabled are sufficiently authenticated after they've logged in with their my.myob credentials. Going further and collecting companyfile username & password is superfluous.

- [x] Update Manager to not expect credentials to exist under `companyfile_credentials`.
- [x] Update readme - suggest dropdown to still be rendered in case user has multiple companyfiles against their account, but don't force username and password to be provided.

**Comment by thegumbyman** [comment]
I also found that passing the `x-myobapi-cftoken` header when using SSO would cause all requests to return 401. Once I removed the header, requests would return as expected.

**Comment by jarekwg** [comment]
> I also found that passing the `x-myobapi-cftoken` header when using SSO would cause all requests to return 401. Once I removed the header, requests would return as expected.

Oh interesting. So I wonder if it's that simple -- we just don't store an entry for the given companyfile under `companyfile_credentials` if the user's account is SSO enabled (something that can be checked easily by trying to hit an endpoint immediately after the initial auth round trip). Then, if the entry's not there, we omit `x-myobapi-cftoken` from the header?
