### ISSUE TITLE
Company list returns blank

### ISSUE THREAD

**Issue by paladin0** [uptick/pymyob#36]
We have checked every step of the auth process, it passes the initial code, then the auth and refresh tokens are provided, we have output all data from the stored creds and it all looks good, when trying the same thing in postman (different keys) i get a company list back. 

Any help would be great because this is all we get back

{
  "company_files": []
}

**Comment by jarekwg** [comment]
Hey @paladin0,

So you're saying `myob.companyfiles.all() == []`?

The only guess I can hazard from this information (the only time I've seen nothing returned), is if the user credentials you've set up the integration with don't have permission to see any company files. If you used the same credentials when testing with postman, then I'm not sure.

Could you give a little more detail in how you're setting up the integration? Did you follow the readme exactly?

**Comment by paladin0** [comment]
Below is the code for after we have returned data from myob (code. etc), the auth process appears to be correct we have watched it in the python console

Using the same credentials we can log using the postman demo (different keys) and manually insert everything into postman and we get results

`@bp.route('/myob_oauth')
def myob_oauth():
    print("=============request json===============")
    print(request.args.get('code'))
    params = request.args.get('code')
    stored_values = OAUTH_PERSISTENT_SERVER_STORAGE
    credentials = PartnerCredentials(**stored_values)

    try:
        credentials.verify(params)

        # Resave our verified credentials
        for key, value in credentials.state.items():
            OAUTH_PERSISTENT_SERVER_STORAGE.update({key: value})

        print(OAUTH_PERSISTENT_SERVER_STORAGE)

        if credentials.verified:
            print("=================== Myob Verify =======================")
            print(credentials.state)
            return redirect(Config.LIVE_URL + "/data/myob_verified")
        
    except:
        return (None, 401)

    return (None, 401)

@bp.route('/myob_verified')
def myob_verified():
    stored_values = OAUTH_PERSISTENT_SERVER_STORAGE
    credentials = PartnerCredentials(**stored_values)

    print("=================== Myob Verify =======================")
    print(stored_values)

    try:
        myob = Myob(credentials)

        company_files = myob.companyfiles.all()

        if company_files.count > 0:
            comp = company_files[0]
            invoices = comp.invoices.all()

            print("========== Invoices ================")
            print(invoices)

            return (jsonify(company_files=company_files,invoices=invoices), 201)

        print("========== Companies ================")
        print(company_files)

        return (jsonify(company_files=company_files), 201)
    except:
        return (jsonify(company_files=[]), 201)`

**Comment by jarekwg** [comment]
Looking at that second blob of code, I see you're returning `company_files=[]` when something goes wrong.
However, you're using a bare `except` clause, which will catch any error under the sun.
You should make the `except` statement very specific, catching only the kinds of errors you expect to see.

In this case, `company_files.count > 0` would raise an error, because `.count` is not how to measure size of lists in python. That line probably should be `len(company_files) > 0`. There may be other errors in the code too. I'd recommend putting a debugger line in there and following it step by step.
