### ISSUE TITLE
KeyError: 'There are no stored username-password credentials for this company id.'

### ISSUE THREAD

**Issue by TST-akimond** [uptick/pymyob#37]
After verification, I get this error while trying to get company files.
KeyError: 'There are no stored username-password credentials for this company id.'

    stored_values = mycache.get('myob_creds')
    credentials = PartnerCredentials(**stored_values)

    print("=================== Myob Verify =======================")
    print(stored_values)

    print("====================1==================")
    myob = Myob(credentials)
    print(credentials)
    print("====================2==================")
    company_files = myob.companyfiles.all()
    print(company_files)
    print("====================2==================")
    
    if len(company_files) > 0:
        print("====================3==================")
        comp = company_files[0]
        print("====================4==================")
        customers = comp.contacts.all()
        print("========== customers ================")
        print(customers)
        return (jsonify(company_files=company_files,customers=customers), 201)

    print("========== Companies ================")
    print(company_files)

I got error at here: 
          customers = comp.contacts.all()

company_files returns this:
[CompanyFile:
	banking
	company
	contacts
	general_ledger
	inventory
	invoices
	orders
	purchase_bills
	purchase_orders]

**Comment by jarekwg** [comment]
There are two sets of credentials that are needed to get into a company file:
- user credentials for MYOB login (you provide these when redirected to MYOB)
- companyfile credentials (without these, you'll only be able to view the company file metadata, but not what's inside)

I think you've skipped over the second credentials. After verification, you need to provide username & password for the company file. See this line from the readme: `cred.authenticate_companyfile(<company_id>, <username>, <password>)`

Please also take a quick look at #18 and #33, which may help clear up some confusion.

**Comment by TST-akimond** [comment]
I added companyfile credentials after verification.

    stored_values = mycache.get('myob_creds')
    credentials = PartnerCredentials(**stored_values)
    credentials.authenticate_companyfile("eb04087e-e429-4471-8e10-4bdcf18282f7", "my-username", "my-password")

and then I got this error at here:
customers = comp.contacts.all()

myob.exceptions.MyobExceptionUnknown: (<Response [500]>, 'Internal Server Error')

**Comment by jarekwg** [comment]
Eh, MYOB 500s are not fun to deal with.
Try to wrap it in a try-except block, and see if there is any additional information in the 500 response:
```
try
    customers = comp.contacts.all()
except Exception as e:
    print(e.response.json())
```
Most likely it'll just be "contact support", but worth checking.

In my experience, I've generally only seen 500s on massive company files, where the MYOB api falls over trying to comb through the data. Is your company file large? (eg. 5+ years of invoicing?)

You could also try hitting some endpoints that aren't expected to be as large (eg. `comp.general_ledger.taxcode()`)
Or, at least slimming down the contacts call to `comp.general_ledger.customer()` or `comp.general_ledger.employee()`.

Lemme know how you go. You can also ask myob support about it.

Cheers,

**Comment by jarekwg** [comment]
Stale, closing.
