### ISSUE TITLE
Support for Report api endpoints

### ISSUE THREAD

**Issue by TST-akimond** [uptick/pymyob#40]
I think, there aren't any supports for /accountright v2/report endpoints.
like this:
      https://developer.myob.com/api/accountright/v2/report/profitandlosssummary/

If there is, please let me know.

**Comment by jarekwg** [comment]
Not at the moment, but feel free to open a PR (define endpoint in endpoints.py, and add a quick test following existing pattern) and I'll be happy to merge and publish promptly.

**Comment by jarekwg** [comment]
Closing. This is easily addable, as with any other missing endpoint. Just need a PR offered up.
