### ISSUE TITLE
Using 'ge' (greater than) and 'le' (less than) in GET filter

### ISSUE THREAD

**Issue by theducvu** [uptick/pymyob#42]
Hi, I recently found out how to use the filter option in my GET functions and it's very helpful:

```python
compfiles.quotes.item(Number='1234')
```

But I'm trying to use 'ge' and 'le' to filter by fields greater than or less than a value. It's talked about [here](https://developer.myob.com/api/accountright/api-overview/retrieving-data/). Something like:

```python
compfiles.inventory.item(Price='ge 10.0')
```
to get items with prices > 10.0.

I cannot find any documentation on this or anything related to it in the code. Is this possible in pymyob?

**Comment by jarekwg** [comment]
Hiya @theducvu,

Sorry about the limited docs. Yes, this is supported. The syntax is `FIELD__gt` and `FIELD__lt`.
Take a look at the tests for some examples: https://github.com/uptick/pymyob/blob/d3cacbcdf09baec0bb58559c6784fb54d3c381d3/tests/test_managers.py#L28

Alternatively, if you want to do something very out-of-the-ordinary, you can pass in a `raw` param and build the query yourself using myob's syntax. Example here:
https://github.com/uptick/pymyob/blob/d3cacbcdf09baec0bb58559c6784fb54d3c381d3/tests/test_managers.py#L30

See also: #8.

**Comment by theducvu** [comment]
Thanks! I should have thought to check tests. Your work and quick responses are really appreciated.
