### ISSUE TITLE
ORM-ify

### ISSUE THREAD

**Issue by jarekwg** [uptick/pymyob#5]
- [ ] Remove the need to pass `company_id` in to every single function. It should get set once at some higher level. Also, this doesn't align with the fact that the credentials for a chosen company file (`userpass`) are stored in the credentials object already. Maybes we just store `companu_id` in there too? 
- [ ] Make methods more django-like (i.e. `.all()`, `.filter()`, etc). This may require a bit more sophistication in the layout of the `endpoints.py` file.
- [ ] Consider parsing responses a little, to return objects rather than raw JSON (not that JSON is that horrible)

**Comment by Aralox** [comment]
I wholeheartedly agree, I do believe ormification is imperative here. If only more developers understood the gravity of the situation like you do. Perhaps with a little work we could succesfully ormify every repository on this blessed version control website.

**Comment by jarekwg** [comment]
Since the credentials object currently stores the authentication credentials for a given company file, it is already specific to the given `company_id`, and hence I feel the two should be together.

However I feel the better solution would be introducing a third object, which takes both the `company_id` and `userpass` and stores them somewhere separately. This would be useful in cases where a single set of PartnerCredentials gives access to multiple company files, which each need their own `company_id` and `userpass` stored somewhere.

**Comment by daughterlycare** [comment]
We could possibly kill two birds with one stone by defining the ORM architecture it while doing this.

```
myob = Myob(cred)

company = myob.companyfiles.get(company_id=<company_id>)
company.authenticate(userpass=userpass)
company.invoices.all()

```

**Comment by jarekwg** [comment]
That looks very attractive!

The only remaining setback I see (with both your proposal and mine) is that it might add some tediousness to storing these credentials, because we'll need to store both the `state` from the `PartnerCredentials`, along with these company_id/userpass pairs, in different places.
If `cred.state` were to also contain a dict of `<company_id>: <userpass>` mappings, then userpass would only need to be fed in once, after which it would be remembered for us.
I guess that could even be done with what you've proposed:
```
# First time
cred = PartnerCredentials(<stored_state>)
myob = Myob(cred)

company = myob.companyfiles.get(company_id=<company_id>)
company.authenticate(userpass=<userpass>)  # passes userpass back into the `cred` instance.
..update our stored state from cred.state
company.invoices.all()

# Future times
cred = PartnerCredentials(<stored_state_w_userpass_for_our_previously_authed_company>)
myob = Myob(cred)

company = myob.companyfiles.get(company_id=<company_id>)
company.invoices.all()  # already authed.
```

**Comment by daughterlycare** [comment]
I see what you mean, having the data traverse upwards to the `Myob` object could prove problematic. 

What if we authenticated the company file using `PartnerCredentials` directly?

```
#First time
cred = PartnerCredentials(<stored_state>)
myob = Myob(cred)

#State is updated with company:userpass dict item
cred.authenticate(company_id=<company_id>, userpass=<userpass>) # you are now authenticated

company = myob.companyfiles.get(company_id=<company_id>)
company.invoices.all()

#Future times
cred = PartnerCredentials(<stored_state_w_userpass_for_our_previously_authed_company>)
myob = Myob(cred)

company = myob.companyfiles.get(company_id=<company_id>)
company.invoices.all() # already authed
```

**Comment by jarekwg** [comment]
Yep looks good. I'd probs adjust the method name in this case to something more like:
`cred.authenticate_company` or `cred.company_login`, but yep. Looks good.
Would also need to ensure that whatever is currently being returned from `myob.companyfiles.get` is not lost when we start returning `Company` objects (if it's important). 

I'll have a crack at making the necessary changes in the coming days. Though if you're keen to submit a PR yourself, I'm happy to review that too. :)
