### ISSUE TITLE
x-myobapi-cftoken header not needed sometimes

### ISSUE THREAD

**Issue by seb-b** [uptick/pymyob#68]
So I think from [googling](https://community.myob.com/t5/MYOB-Business-API/x-myobapi-cftoken/td-p/608438), if you are attached to a CompanyFile via my.myob.com you do not require the `x-myobapi-cftoken` header, and in fact when I do try to use it, I get a 401 (???). When I manually delete the header from `request_kwargs` before hitting an endpoint everything works ok, but if don't authenticate with a CompanyFile I get a `KeyError('There are no stored username-password credentials for this company id.')`

Is it possible to make the CF authentication optional? This project is great for helping with the nasty oauth flow I'd love to keep using it for the CRUD operations too

**Comment by jarekwg** [comment]
Hey @seb-b,

Thanks for your message. Might this be a dupe of #33?
I'd love to deal with it, but our resourcing is a little slim at the moment. Happy to review a PR though if you want to put one forward.

**Comment by seb-b** [comment]
oh yep this is definitely a duplicate, same issue, I'll close this one.
