### ISSUE TITLE
Using this library with an access_token rather than creds

### ISSUE THREAD

**Issue by drewbroadley** [uptick/pymyob#73]
Hi there,

I've successfully got a flow working with OAuth 2.0 that gets me an MYOB Token.

However, the way this "creds" needs to be saved/stored, goes against my method of storing and refreshing tokens through a seperate OAuth flow. This is not ideal for me as I am also connecting to Xero and other accounting packages.

These other libraries use the token and expose methods to set the token for the SDK, and then from there I can query the endpoints.

Is there a possible way of doing this with this SDK?

**Comment by drewbroadley** [comment]
Ah, figured it out for those who are also interested:

`myob_cred = PartnerCredentials(
        consumer_key=os.getenv("CONNECTOR_MYOB_CLIENT_ID"),
        consumer_secret=os.getenv("CONNECTOR_MYOB_CLIENT_SECRET"),
        callback_uri=os.getenv("CONNECTOR_MYOB_CALLBACK_URL"),
        verified=True,
        oauth_token=<access_token>
    )`

**Comment by jarekwg** [comment]
Glad you got it sorted! Yeah we're not particularly prescriptive with how you store these.

**Comment by drewbroadley** [comment]
Not a problem, was easy enough to figure out and noted here if anyone needs it in the future!
