### ISSUE TITLE
How does one use $top, $filter, etc. ?

### ISSUE THREAD

**Issue by drewbroadley** [uptick/pymyob#74]
As per MYOB API documentation:
https://developer.myob.com/api/myob-business-api/api-overview/retrieving-data

I can see they have methods such as `$top`, `$filter`, etc. and for the life of me I can see in the manager.py there is handling of these, but since you can't send them directly with the '$' due to kwargs not liking that in the key, how do you access these params to the API?

I tried documentation, nothing, I tried tests, nothing (other than 'data' or 'uid').

Please help with an example!

**Comment by drewbroadley** [comment]
Once again, figured it out with some pain and trial and error.

For those wondering:

`
self.company.banking.spendmoneytxn(
   raw_filter="Date ge datetime'2023-01-01'"
)
`

**Comment by jarekwg** [comment]
Yep that's right.
We've wrapped filtering and pagination with something nicer on the eyes; advanced filtering is supported through use of the `raw_filter` param.
See the tests for some more examples. Simple equality and "greater than"/"less than" checks can be done without writing raw filters.
https://github.com/uptick/pymyob/blob/master/tests/test_managers.py#L24-L33

**Comment by jarekwg** [comment]
ie, for your case, you can just do: 
```
self.company.banking.spendmoneytxn(Date__gt=datetime.date(2023, 1, 1), page=page, limit=100)
```

**Comment by drewbroadley** [comment]
Appreciate it, that'll be nice to use actual datetime objects that way too.
