### ISSUE TITLE
Support for `gt` and `lt` filtering.

### ISSUE THREAD

**Issue by bartonip** [uptick/pymyob#8]
Hi there, 

I can't find anything about this in the documentation, but does pymyob support query strings?

Thanks
Barton

**Comment by jarekwg** [comment]
Hi bartonip,

It'll build the querystring for you from the kwargs you provide to the method.
These kwargs get special treatment: `['orderby', 'format', 'headers', 'page', 'limit', 'templatename']`.
Any other kwargs you've passed in will be converted into a list of `eq`s and used in the `$filter` query.
See here for exact logic: https://github.com/uptick/pymyob/blob/master/myob/managers.py#L64-L100

This enables calls such as:
`invoices = myob.invoices.all(company_id=<company_id>, InvoiceType='Item', orderby='Number desc')`
Take a look through the README for more examples.

Is there something specific you're after?

**Comment by bartonip** [comment]
Thanks for the prompt reply, I was hoping to filter invoices by StartDate/EndDate. Is that possible? MYOB's documentation on query strings isn't that great.

**Comment by jarekwg** [comment]
If the above doesn't fix your problem, then it'll definitely be addressed in #13

**Comment by jarekwg** [comment]
^ published in 0.4.3
